export const Types = {
  FETCH_PRODUCTS_DATA: "FETCH_PRODUCTS_DATA",
  FETCH_PRODUCTS_DATA_SUCCESS: "FETCH_PRODUCTS_DATA_SUCCESS",
  FETCH_PRODUCTS_DATA_FAILED: "FETCH_PRODUCTS_DATA_FAILED",

  FETCH_PRODUCTS_FILTER: "FETCH_PRODUCTS_FILTER",
  FETCH_PRODUCTS_FILTER_SUCCESS: "FETCH_PRODUCTS_FILTER_SUCCESS",
  FETCH_PRODUCTS_FILTER_FAILED: "FETCH_PRODUCTS_FILTER_FAILED",

  FETCH_PRODUCTS_SUBIVISION: "FETCH_PRODUCTS_SUBIVISION",
  FETCH_PRODUCTS_SUBIVISION_SUCCESS: "FETCH_PRODUCTS_SUBIVISION_SUCCESS",
  FETCH_PRODUCTS_SUBIVISION_FAILED: "FETCH_PRODUCTS_SUBIVISION_FAILED",
};
