export const Types = {
  FETCH_AMAZINGOFFER: "FETCH_AMAZINGOFFER",
  FETCH_AMAZINGOFFER_SUCCESS: "FETCH_AMAZINGOFFER_SUCCESS",
  FETCH_AMAZINGOFFER_FAILED: "FETCH_AMAZINGOFFER_FAILED",

  FETCH_BESTSELLERS: "FETCH_BESTSELLERS",
  FETCH_BESTSELLERS_SUCCESS: "FETCH_BESTSELLERS_SUCCESS",
  FETCH_BESTSELLERS_FAILED: "FETCH_BESTSELLERS_FAILED",

  FETCH_NEWEST: "FETCH_NEWEST",
  FETCH_NEWEST_SUCCESS: "FETCH_NEWEST_SUCCESS",
  FETCH_NEWEST_FAILED: "FETCH_NEWEST_FAILED",
};
